import csv


with open('data/scats_raw.csv') as csv_file:
    csv_reader = csv.DictReader(csv_file)
    line_count = 0
    with open('data/scats_converted.csv', mode='w', newline='') as write_csv_file:
        fieldnames = ['SCATS Number', 'Date/Time', 'Traffic Amount']
        writer = csv.DictWriter(write_csv_file, fieldnames=fieldnames)
        writer.writeheader()

        for row in csv_reader:
            if line_count == 0:
                print(f'Column names are {", ".join(row)}')
                line_count += 1
            writer.writerow({'SCATS Number': row["SCATS Number"], 'Date/Time': row["Date"] + " 0:00", 'Traffic Amount': row["0:00"]})
            writer.writerow({'SCATS Number': row["SCATS Number"], 'Date/Time': row["Date"] + " 0:15", 'Traffic Amount': row["0:15"]})
            writer.writerow({'SCATS Number': row["SCATS Number"], 'Date/Time': row["Date"] + " 0:30", 'Traffic Amount': row["0:30"]})
            writer.writerow({'SCATS Number': row["SCATS Number"], 'Date/Time': row["Date"] + " 0:45", 'Traffic Amount': row["0:45"]})
            writer.writerow({'SCATS Number': row["SCATS Number"], 'Date/Time': row["Date"] + " 1:00", 'Traffic Amount': row["1:00"]})
            writer.writerow({'SCATS Number': row["SCATS Number"], 'Date/Time': row["Date"] + " 1:15", 'Traffic Amount': row["1:15"]})
            writer.writerow({'SCATS Number': row["SCATS Number"], 'Date/Time': row["Date"] + " 1:30", 'Traffic Amount': row["1:30"]})
            writer.writerow({'SCATS Number': row["SCATS Number"], 'Date/Time': row["Date"] + " 1:45", 'Traffic Amount': row["1:45"]})
            writer.writerow({'SCATS Number': row["SCATS Number"], 'Date/Time': row["Date"] + " 2:00", 'Traffic Amount': row["2:00"]})
            writer.writerow({'SCATS Number': row["SCATS Number"], 'Date/Time': row["Date"] + " 2:15", 'Traffic Amount': row["2:15"]})
            writer.writerow({'SCATS Number': row["SCATS Number"], 'Date/Time': row["Date"] + " 2:30", 'Traffic Amount': row["2:30"]})
            writer.writerow({'SCATS Number': row["SCATS Number"], 'Date/Time': row["Date"] + " 2:45", 'Traffic Amount': row["2:45"]})
            writer.writerow({'SCATS Number': row["SCATS Number"], 'Date/Time': row["Date"] + " 3:15", 'Traffic Amount': row["3:15"]})
            writer.writerow({'SCATS Number': row["SCATS Number"], 'Date/Time': row["Date"] + " 3:30", 'Traffic Amount': row["3:30"]})
            writer.writerow({'SCATS Number': row["SCATS Number"], 'Date/Time': row["Date"] + " 3:45", 'Traffic Amount': row["3:45"]})
            writer.writerow({'SCATS Number': row["SCATS Number"], 'Date/Time': row["Date"] + " 4:00", 'Traffic Amount': row["4:00"]})
            writer.writerow({'SCATS Number': row["SCATS Number"], 'Date/Time': row["Date"] + " 4:15", 'Traffic Amount': row["4:15"]})
            writer.writerow({'SCATS Number': row["SCATS Number"], 'Date/Time': row["Date"] + " 4:30", 'Traffic Amount': row["4:30"]})
            writer.writerow({'SCATS Number': row["SCATS Number"], 'Date/Time': row["Date"] + " 4:45", 'Traffic Amount': row["4:45"]})
            writer.writerow({'SCATS Number': row["SCATS Number"], 'Date/Time': row["Date"] + " 5:00", 'Traffic Amount': row["5:00"]})
            writer.writerow({'SCATS Number': row["SCATS Number"], 'Date/Time': row["Date"] + " 5:15", 'Traffic Amount': row["5:15"]})
            writer.writerow({'SCATS Number': row["SCATS Number"], 'Date/Time': row["Date"] + " 5:30", 'Traffic Amount': row["5:30"]})
            writer.writerow({'SCATS Number': row["SCATS Number"], 'Date/Time': row["Date"] + " 5:45", 'Traffic Amount': row["5:45"]})
            writer.writerow({'SCATS Number': row["SCATS Number"], 'Date/Time': row["Date"] + " 6:00", 'Traffic Amount': row["6:00"]})
            writer.writerow({'SCATS Number': row["SCATS Number"], 'Date/Time': row["Date"] + " 6:15", 'Traffic Amount': row["6:15"]})
            writer.writerow({'SCATS Number': row["SCATS Number"], 'Date/Time': row["Date"] + " 6:30", 'Traffic Amount': row["6:30"]})
            writer.writerow({'SCATS Number': row["SCATS Number"], 'Date/Time': row["Date"] + " 6:45", 'Traffic Amount': row["6:45"]})
            writer.writerow({'SCATS Number': row["SCATS Number"], 'Date/Time': row["Date"] + " 7:00", 'Traffic Amount': row["7:00"]})
            writer.writerow({'SCATS Number': row["SCATS Number"], 'Date/Time': row["Date"] + " 7:15", 'Traffic Amount': row["7:15"]})
            writer.writerow({'SCATS Number': row["SCATS Number"], 'Date/Time': row["Date"] + " 7:30", 'Traffic Amount': row["7:30"]})
            writer.writerow({'SCATS Number': row["SCATS Number"], 'Date/Time': row["Date"] + " 7:45", 'Traffic Amount': row["7:45"]})
            writer.writerow({'SCATS Number': row["SCATS Number"], 'Date/Time': row["Date"] + " 8:00", 'Traffic Amount': row["8:00"]})
            writer.writerow({'SCATS Number': row["SCATS Number"], 'Date/Time': row["Date"] + " 8:15", 'Traffic Amount': row["8:15"]})
            writer.writerow({'SCATS Number': row["SCATS Number"], 'Date/Time': row["Date"] + " 8:30", 'Traffic Amount': row["8:30"]})
            writer.writerow({'SCATS Number': row["SCATS Number"], 'Date/Time': row["Date"] + " 8:45", 'Traffic Amount': row["8:45"]})
            writer.writerow({'SCATS Number': row["SCATS Number"], 'Date/Time': row["Date"] + " 9:00", 'Traffic Amount': row["9:00"]})
            writer.writerow({'SCATS Number': row["SCATS Number"], 'Date/Time': row["Date"] + " 9:15", 'Traffic Amount': row["9:15"]})
            writer.writerow({'SCATS Number': row["SCATS Number"], 'Date/Time': row["Date"] + " 9:30", 'Traffic Amount': row["9:30"]})
            writer.writerow({'SCATS Number': row["SCATS Number"], 'Date/Time': row["Date"] + " 9:45", 'Traffic Amount': row["9:45"]})
            writer.writerow({'SCATS Number': row["SCATS Number"], 'Date/Time': row["Date"] + " 10:00", 'Traffic Amount': row["10:00"]})
            writer.writerow({'SCATS Number': row["SCATS Number"], 'Date/Time': row["Date"] + " 10:15", 'Traffic Amount': row["10:15"]})
            writer.writerow({'SCATS Number': row["SCATS Number"], 'Date/Time': row["Date"] + " 10:30", 'Traffic Amount': row["10:30"]})
            writer.writerow({'SCATS Number': row["SCATS Number"], 'Date/Time': row["Date"] + " 10:45", 'Traffic Amount': row["10:45"]})
            writer.writerow({'SCATS Number': row["SCATS Number"], 'Date/Time': row["Date"] + " 11:00", 'Traffic Amount': row["11:00"]})
            writer.writerow({'SCATS Number': row["SCATS Number"], 'Date/Time': row["Date"] + " 11:15", 'Traffic Amount': row["11:15"]})
            writer.writerow({'SCATS Number': row["SCATS Number"], 'Date/Time': row["Date"] + " 11:30", 'Traffic Amount': row["11:30"]})
            writer.writerow({'SCATS Number': row["SCATS Number"], 'Date/Time': row["Date"] + " 11:45", 'Traffic Amount': row["11:45"]})
            writer.writerow({'SCATS Number': row["SCATS Number"], 'Date/Time': row["Date"] + " 12:00", 'Traffic Amount': row["12:00"]})
            writer.writerow({'SCATS Number': row["SCATS Number"], 'Date/Time': row["Date"] + " 12:15", 'Traffic Amount': row["12:15"]})
            writer.writerow({'SCATS Number': row["SCATS Number"], 'Date/Time': row["Date"] + " 12:30", 'Traffic Amount': row["12:30"]})
            writer.writerow({'SCATS Number': row["SCATS Number"], 'Date/Time': row["Date"] + " 12:45", 'Traffic Amount': row["12:45"]})
            writer.writerow({'SCATS Number': row["SCATS Number"], 'Date/Time': row["Date"] + " 13:00", 'Traffic Amount': row["13:00"]})
            writer.writerow({'SCATS Number': row["SCATS Number"], 'Date/Time': row["Date"] + " 13:15", 'Traffic Amount': row["13:15"]})
            writer.writerow({'SCATS Number': row["SCATS Number"], 'Date/Time': row["Date"] + " 13:30", 'Traffic Amount': row["13:30"]})
            writer.writerow({'SCATS Number': row["SCATS Number"], 'Date/Time': row["Date"] + " 13:45", 'Traffic Amount': row["13:45"]})
            writer.writerow({'SCATS Number': row["SCATS Number"], 'Date/Time': row["Date"] + " 14:00", 'Traffic Amount': row["14:00"]})
            writer.writerow({'SCATS Number': row["SCATS Number"], 'Date/Time': row["Date"] + " 14:15", 'Traffic Amount': row["14:15"]})
            writer.writerow({'SCATS Number': row["SCATS Number"], 'Date/Time': row["Date"] + " 14:30", 'Traffic Amount': row["14:30"]})
            writer.writerow({'SCATS Number': row["SCATS Number"], 'Date/Time': row["Date"] + " 14:45", 'Traffic Amount': row["14:45"]})
            writer.writerow({'SCATS Number': row["SCATS Number"], 'Date/Time': row["Date"] + " 15:00", 'Traffic Amount': row["15:00"]})
            writer.writerow({'SCATS Number': row["SCATS Number"], 'Date/Time': row["Date"] + " 15:15", 'Traffic Amount': row["15:15"]})
            writer.writerow({'SCATS Number': row["SCATS Number"], 'Date/Time': row["Date"] + " 15:30", 'Traffic Amount': row["15:30"]})
            writer.writerow({'SCATS Number': row["SCATS Number"], 'Date/Time': row["Date"] + " 15:45", 'Traffic Amount': row["15:45"]})
            writer.writerow({'SCATS Number': row["SCATS Number"], 'Date/Time': row["Date"] + " 16:00", 'Traffic Amount': row["16:00"]})
            writer.writerow({'SCATS Number': row["SCATS Number"], 'Date/Time': row["Date"] + " 16:15", 'Traffic Amount': row["16:15"]})
            writer.writerow({'SCATS Number': row["SCATS Number"], 'Date/Time': row["Date"] + " 16:30", 'Traffic Amount': row["16:30"]})
            writer.writerow({'SCATS Number': row["SCATS Number"], 'Date/Time': row["Date"] + " 16:45", 'Traffic Amount': row["16:45"]})
            writer.writerow({'SCATS Number': row["SCATS Number"], 'Date/Time': row["Date"] + " 17:00", 'Traffic Amount': row["17:00"]})
            writer.writerow({'SCATS Number': row["SCATS Number"], 'Date/Time': row["Date"] + " 17:15", 'Traffic Amount': row["17:15"]})
            writer.writerow({'SCATS Number': row["SCATS Number"], 'Date/Time': row["Date"] + " 17:30", 'Traffic Amount': row["17:30"]})
            writer.writerow({'SCATS Number': row["SCATS Number"], 'Date/Time': row["Date"] + " 17:45", 'Traffic Amount': row["17:45"]})
            writer.writerow({'SCATS Number': row["SCATS Number"], 'Date/Time': row["Date"] + " 18:00", 'Traffic Amount': row["18:00"]})
            writer.writerow({'SCATS Number': row["SCATS Number"], 'Date/Time': row["Date"] + " 18:15", 'Traffic Amount': row["18:15"]})
            writer.writerow({'SCATS Number': row["SCATS Number"], 'Date/Time': row["Date"] + " 18:30", 'Traffic Amount': row["18:30"]})
            writer.writerow({'SCATS Number': row["SCATS Number"], 'Date/Time': row["Date"] + " 18:45", 'Traffic Amount': row["18:45"]})
            writer.writerow({'SCATS Number': row["SCATS Number"], 'Date/Time': row["Date"] + " 19:00", 'Traffic Amount': row["19:00"]})
            writer.writerow({'SCATS Number': row["SCATS Number"], 'Date/Time': row["Date"] + " 19:15", 'Traffic Amount': row["19:15"]})
            writer.writerow({'SCATS Number': row["SCATS Number"], 'Date/Time': row["Date"] + " 19:30", 'Traffic Amount': row["19:30"]})
            writer.writerow({'SCATS Number': row["SCATS Number"], 'Date/Time': row["Date"] + " 19:45", 'Traffic Amount': row["19:45"]})
            writer.writerow({'SCATS Number': row["SCATS Number"], 'Date/Time': row["Date"] + " 20:00", 'Traffic Amount': row["20:00"]})
            writer.writerow({'SCATS Number': row["SCATS Number"], 'Date/Time': row["Date"] + " 20:15", 'Traffic Amount': row["20:15"]})
            writer.writerow({'SCATS Number': row["SCATS Number"], 'Date/Time': row["Date"] + " 20:30", 'Traffic Amount': row["20:30"]})
            writer.writerow({'SCATS Number': row["SCATS Number"], 'Date/Time': row["Date"] + " 20:45", 'Traffic Amount': row["20:45"]})
            writer.writerow({'SCATS Number': row["SCATS Number"], 'Date/Time': row["Date"] + " 21:00", 'Traffic Amount': row["21:00"]})
            writer.writerow({'SCATS Number': row["SCATS Number"], 'Date/Time': row["Date"] + " 21:15", 'Traffic Amount': row["21:15"]})
            writer.writerow({'SCATS Number': row["SCATS Number"], 'Date/Time': row["Date"] + " 21:30", 'Traffic Amount': row["21:30"]})
            writer.writerow({'SCATS Number': row["SCATS Number"], 'Date/Time': row["Date"] + " 21:45", 'Traffic Amount': row["21:45"]})
            writer.writerow({'SCATS Number': row["SCATS Number"], 'Date/Time': row["Date"] + " 22:00", 'Traffic Amount': row["22:00"]})
            writer.writerow({'SCATS Number': row["SCATS Number"], 'Date/Time': row["Date"] + " 22:15", 'Traffic Amount': row["22:15"]})
            writer.writerow({'SCATS Number': row["SCATS Number"], 'Date/Time': row["Date"] + " 22:30", 'Traffic Amount': row["22:30"]})
            writer.writerow({'SCATS Number': row["SCATS Number"], 'Date/Time': row["Date"] + " 22:45", 'Traffic Amount': row["22:45"]})
            writer.writerow({'SCATS Number': row["SCATS Number"], 'Date/Time': row["Date"] + " 23:00", 'Traffic Amount': row["23:00"]})
            writer.writerow({'SCATS Number': row["SCATS Number"], 'Date/Time': row["Date"] + " 23:15", 'Traffic Amount': row["23:15"]})
            writer.writerow({'SCATS Number': row["SCATS Number"], 'Date/Time': row["Date"] + " 23:30", 'Traffic Amount': row["23:30"]})
            writer.writerow({'SCATS Number': row["SCATS Number"], 'Date/Time': row["Date"] + " 23:45", 'Traffic Amount': row["23:45"]})
            line_count += 1
        print(f'Processed {line_count} lines.')
