<Menu>:
    startScats: startScats
    endScats: endScats
    day: day
    startTime: startTime
    endTime: endTime
    direction: direction
    prediction: prediction


    
    GridLayout:
        cols: 2
        # size: root.width - 450, root.height
        size: root.size
        # pos: 0,100
        
    
        GridLayout:
            cols: 2
            

            Label:
                text: "Start Scats Point: "

            TextInput:
                id: startScats
                multiline: False

            Label:
                text: "End Scats Point: "

            TextInput:
                id: endScats
                multiline: False
            
            Label:
                text: "Enter day 0=mon etc "

            TextInput:
                id: day
                multiline: False

            Label:
                text: "Start time: "

            TextInput:
                id: startTime
                multiline: False

            Label:
                text: "End time: "

            TextInput:
                id: endTime
                multiline: False

            Label:
                text: "Direction: "

            TextInput:
                id: direction
                multiline: False 

            Button:
                text: "Get Shortest Route"
                font_size: 20
                size: 175, 50
                size_hint: None, None # <--
                on_press: root.getRoute()

            Button:
                text: "Run Prediction"
                font_size: 20
                size: 175, 50
                size_hint: None, None # <--
                on_press: root.prediction()
            
        BoxLayout: 
            orientation: "horizontal"
            size: self.size
            id: mapFigure

        GridLayout:
            cols: 1
            row_default_height: 40
            # size: root.width, 150
            Label:
                size_hint_y:None
                height: 30 
                text: "Output: "

            Label:
                size_hint_y:None
                height: 30 
                id: prediction
                text: ""
        
        
